### ISSUE TITLE
SPARQL query yields different results in 4store and AllegroGraph (AG)

### ISSUE THREAD

**Issue by mdorf** [ncbo/goo#135]
The following SPARQL query is executed on a test data in a GOO test `goo/test/test_where/test_aggregated`:

```sparql
SELECT DISTINCT ?id ( COUNT(DISTINCT ?category_agg_count) AS ?category_agg_count_projection )
FROM <http://goo.org/default/Student> 
FROM <http://goo.org/default/Program>
WHERE { ?id a <http://goo.org/default/Student> .
	OPTIONAL { ?id <http://goo.org/default/enrolled> ?enrolled_agg_count .  }        
	OPTIONAL { ?enrolled_agg_count <http://goo.org/default/category> ?category_agg_count .  }    
}
GROUP BY ?id
```
In **4store**, it returns the expected results:

<img width="464" alt="Screen Shot 2023-02-03 at 8 32 05 AM" src="https://user-images.githubusercontent.com/2042070/216656504-c2e83cf6-98c0-428a-9cfc-b06d4ee7a4c9.png">

In **AllegroGraph**, the results are wrong:

<img width="411" alt="Screen Shot 2023-02-03 at 10 30 08 AM" src="https://user-images.githubusercontent.com/2042070/216680156-fb7a2ca0-c399-4bd2-a850-77fcb1cfa53f.png">

If I remove the `OPTIONAL` clauses from the query in **AllegroGraph**, the query runs correctly:

```sparql
SELECT DISTINCT ?id ( COUNT(DISTINCT ?category_agg_count) AS ?category_agg_count_projection )
FROM <http://goo.org/default/Student> 
FROM <http://goo.org/default/Program>
WHERE { ?id a <http://goo.org/default/Student> .
	?id <http://goo.org/default/enrolled> ?enrolled_agg_count .  
	?enrolled_agg_count <http://goo.org/default/category> ?category_agg_count .
}
GROUP BY ?id
```

<img width="409" alt="Screen Shot 2023-02-03 at 10 34 07 AM" src="https://user-images.githubusercontent.com/2042070/216680635-dc1958df-12d1-4389-914d-024202f69d5d.png">

This issue has not been detected earlier since we haven't enabled the ability to run GOO unit tests with AllegroGraph until recently.

**Comment by mdorf** [comment]
It's worth noting that this query cannot be easily modified in our code, since it's generated via this GOO API call:
```ruby
# Categories per student program categories
sts = Student.where.include(:name).aggregate(:count, enrolled: [:category]).all
```

**Comment by jonquet** [comment]
Hello. My feeling is that 4store is not right and Allegro is correct in requesting the removal of the OPTIONAL clauses.
See : https://jena.apache.org/tutorials/sparql_optionals.html

Especially : "If the first optional binds ?name and ?x to some values, the second OPTIONAL is an attempt to match the ground triples (?x and ?name have values). If the first optional did not match the optional part, then the second one is an attempt to match its triple with two variables."

**Comment by syphax-bouazzouni** [comment]
> The solution to this issue will be rolled into the AllegroGraph v7.4 release. It is not available as a standalone patch.

The test is now running using [franzinc/agraph:v8.0.0.rc1](https://hub.docker.com/layers/franzinc/agraph/v8.0.0.rc1/images/sha256-da6d7b9363768057c4c45be5899c7379f137febd08128259d701fe665768a3d7?context=explore)
